docs(GED): add API documentation
MyUnisoft/api-partenaires pull request #100
Opened 2024-11-19 08:20 UTC by Dafyh

2024-11-23 13:38 UTC, fraxken commented on docs/ged.md
> +| `uuid` | Un [identifiant unique universel version 5](https://fr.wikipedia.org/wiki/Universally_unique_identifier) pouvant être utilisé par nos partenaires. |
c'est un UUID v4 non?

2024-11-23 13:38 UTC, fraxken commented on docs/ged.md
> +Cet endpoint permet de d'upload un document sur MyUnisoft.
```suggestion
Cet endpoint permet d'upload un document sur MyUnisoft. 
```

2024-11-23 13:41 UTC, fraxken commented on docs/ged.md
> +Cet endpoint permet d'obtenir la donnée brute du document.
```suggestion
Cet endpoint permet d'obtenir la donnée brute du document (le télécharger).
```

2024-11-23 13:41 UTC, fraxken commented on docs/ged.md
> +::: details Obtenir la donnée brute du document
le côté donnée brute c'est pas forcément clair

2024-11-23 13:44 UTC, fraxken requested changes

2024-11-23 13:44 UTC, fraxken commented on docs/ged.md
> +:::
le details ici rajoute de la surcharge visuelle (autant mettre le texte directement)

2024-11-23 13:44 UTC, fraxken commented on docs/ged.md
> +::: details Nous envoyer un document <a id="upload"></a>
tu devrais faire une section plutôt qu'un details (ici ça surcharge trop surtout avec les sous-details dérrière).

2024-11-25 07:47 UTC, Dafyh commented on docs/ged.md
> +| `uuid` | Un [identifiant unique universel version 5](https://fr.wikipedia.org/wiki/Universally_unique_identifier) pouvant être utilisé par nos partenaires. |
Nop c'est bien du v5

2024-11-27 12:31 UTC, fraxken approved these changes

2024-11-27 12:33 UTC, merged