docs: update auth guide
MyUnisoft/api-partenaires pull request #30
Opened 2023-07-07 14:46 UTC by SofianD

2023-07-07 14:53 UTC, fraxken requested changes

2023-07-07 14:53 UTC, fraxken commented on docs/auth.md
> +Sur cette ligne, vous devriez voir apparaitre la mention `En attante de connexion`. Ce message disparaitra dès que la clé sera activée ou utilisée.
typo `En attente de connexion`

2023-07-07 14:53 UTC, fraxken commented on docs/auth.md
> +## Déconnexion d'une clé
Peut-être une note/warning sur le retour erreur quand la clé est révoquée?

2023-07-07 15:04 UTC, SofianD commented on docs/auth.md
> +Sur cette ligne, vous devriez voir apparaitre la mention `En attante de connexion`. Ce message disparaitra dès que la clé sera activée ou utilisée.
Oh la dinguerie

2023-07-11 09:43 UTC, fraxken approved these changes

2023-07-11 10:13 UTC, merged